config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'
  # authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  # endf

  HighVoltage.configure do |config|
    config.home_page = 'home'
  end

  resources :podcasts do
    resources :episodes
    collection do
      get :search
    end
  end
  resources :users

  get '/auth/:provider/callback' => 'sessions#create'
  get '/signin' => 'sessions#new', :as => :signin
  get '/signout' => 'sessions#destroy', :as => :signout
  get '/auth/failure' => 'sessions#failure'
end

app/models/episode.rb
class Episode < ActiveRecord::Base
  belongs_to :podcast
  has_many :settings
end

app/models/podcast.rb
class Podcast < ActiveRecord::Base
  has_many :episodes
  has_many :settings

  validates :rss_feed, presence: true, uniqueness: true
end

app/models/setting.rb
class Setting < ActiveRecord::Base
  belongs_to :user
  belongs_to :podcast
  belongs_to :episode
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :settings

  enum role: [:user, :vip, :admin]
  after_initialize :set_default_role, :if => :new_record?

  def set_default_role
    if User.count == 0
      self.role ||= :admin
    else
      self.role ||= :user
    end
  end

  def self.create_with_omniauth(auth)
    create! do |user|
      user.provider = auth['provider']
      user.uid = auth['uid']
      if auth['info']
         user.name = auth['info']['name'] || ""
      end
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :check_sidekiq_in_dev

  helper_method :current_user
  helper_method :user_signed_in?
  helper_method :correct_user?

  private
    def current_user
      begin
        @current_user ||= User.find(session[:user_id]) if session[:user_id]
      rescue Exception => e
        nil
      end
    end

    def user_signed_in?
      return true if current_user
    end

    def correct_user?
      @user = User.find(params[:id])
      unless current_user == @user
        redirect_to root_url, :alert => "Access denied."
      end
    end

    def authenticate_user!
      if !current_user
        redirect_to root_url, :alert => 'You need to sign in for access to this page.'
      end
    end

    def check_sidekiq_in_dev
      if Rails.env.development?
        require 'sidekiq/api'
        unless Sidekiq::ProcessSet.new.any?
          flash.now[:danger] = "Sidekiq is not running!"
        end
      end
    end

end

app/controllers/episodes_controller.rb
class EpisodesController < ApplicationController
  before_action :set_episode, only: [:show, :edit, :update, :destroy]
  before_action :set_podcast

  # GET /episodes
  # GET /episodes.json
  def index
    @episodes = Episode.all
  end

  # GET /episodes/1
  # GET /episodes/1.json
  def show
    @setting = Setting.new(play_time: 3, pause_time: 5, rewind_time: 4)
  end

  # GET /episodes/new
  def new
    @episode = Episode.new
  end

  # GET /episodes/1/edit
  def edit
  end

  # POST /episodes
  # POST /episodes.json
  def create
    @episode = Episode.new(episode_params)

    respond_to do |format|
      if @episode.save
        format.html { redirect_to @episode, notice: 'Episode was successfully created.' }
        format.json { render :show, status: :created, location: @episode }
      else
        format.html { render :new }
        format.json { render json: @episode.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /episodes/1
  # PATCH/PUT /episodes/1.json
  def update
    respond_to do |format|
      if @episode.update(episode_params)
        format.html { redirect_to @episode, notice: 'Episode was successfully updated.' }
        format.json { render :show, status: :ok, location: @episode }
      else
        format.html { render :edit }
        format.json { render json: @episode.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /episodes/1
  # DELETE /episodes/1.json
  def destroy
    @episode.destroy
    respond_to do |format|
      format.html { redirect_to episodes_url, notice: 'Episode was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_episode
      @episode = Episode.find(params[:id])
    end

    def set_podcast
      @podcast = Podcast.find(params[:podcast_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def episode_params
      params.require(:episode).permit(:name, :podcast_id)
    end
end

app/controllers/podcasts_controller.rb
class PodcastsController < ApplicationController
  before_action :set_podcast, only: [:show, :edit, :update, :destroy]

  # GET /podcasts
  # GET /podcasts.json
  def index
    @podcasts = Podcast.all
  end

  # GET /podcasts/1
  # GET /podcasts/1.json
  def show
  end

  # GET /podcasts/new
  def new
    @podcast = Podcast.new
  end

  # GET /podcasts/1/edit
  def edit
  end

  # POST /podcasts
  # POST /podcasts.json
  def create
    @podcast = Podcast.new(podcast_params)

    respond_to do |format|
      if @podcast.save
        format.html { redirect_to @podcast, notice: 'Podcast was successfully created.' }
        format.json { render :show, status: :created, location: @podcast }
      else
        format.html { render :new }
        format.json { render json: @podcast.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /podcasts/1
  # PATCH/PUT /podcasts/1.json
  def update
    respond_to do |format|
      if @podcast.update(podcast_params)
        format.html { redirect_to @podcast, notice: 'Podcast was successfully updated.' }
        format.json { render :show, status: :ok, location: @podcast }
      else
        format.html { render :edit }
        format.json { render json: @podcast.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /podcasts/1
  # DELETE /podcasts/1.json
  def destroy
    @podcast.destroy
    respond_to do |format|
      format.html { redirect_to podcasts_url, notice: 'Podcast was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_podcast
      @podcast = Podcast.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def podcast_params
      params.require(:podcast).permit(:name, :rss_feed)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    redirect_to '/auth/twitter'
  end

  def create
    auth = request.env["omniauth.auth"]
    user = User.where(:provider => auth['provider'],
                      :uid => auth['uid'].to_s).first || User.create_with_omniauth(auth)
    reset_session
    session[:user_id] = user.id
    redirect_to root_url, :notice => 'Signed in!'
  end

  def destroy
    reset_session
    redirect_to root_url, :notice => 'Signed out!'
  end

  def failure
    redirect_to root_url, :alert => "Authentication error: #{params[:message].humanize}"
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :correct_user?, :except => [:index]

  def index
    @users = User.all
    authorize User
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(secure_params)
      redirect_to @user
    else
      render :edit
    end
  end

  def show
    @user = User.find(params[:id])
    authorize @user
  end

  private

  def secure_params
    params.require(:user).permit(:email)
  end

end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/episodes_helper.rb
module EpisodesHelper
end

app/helpers/podcasts_helper.rb
module PodcastsHelper
end

app/views/episodes/_form.html.erb
<%= simple_form_for(@episode) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.association :podcast %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/episodes/edit.html.erb
<h1>Editing Episode</h1>

<%= render 'form' %>

<%= link_to 'Show', @episode %> |
<%= link_to 'Back', episodes_path %>

app/views/episodes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Episodes</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Podcast</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @episodes.each do |episode| %>
      <tr>
        <td><%= link_to episode.name, [@podcast, episode] %></td>
        <td><%= link_to episode.podcast.name, episode.podcast %></td>
        <td><%= link_to 'Edit', edit_podcast_episode_path(@podcast, episode) %></td>
        <td><%= link_to 'Destroy', [@podcast, episode], method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Episode', new_podcast_episode_path(@podcast) %>

app/views/episodes/new.html.erb
<h1>New Episode</h1>

<%= render 'form' %>

<%= link_to 'Back', episodes_path %>

app/views/episodes/show.html.erb
<% content_for :title do %>Episode<% end %>

<div class="row">
  <div class="text-center">
    <h3><%= @episode.podcast.name %> - <%= @episode.name %></h3>
    <div>
      <audio class="hide" id="audioPlayer" controls preload="none" style="width: 400px;">
        <!-- <source src="track.ogg" type="audio/ogg" /> -->
        <source src="http://traffic.libsyn.com/atpfm/atp131.mp3" type="audio/mpeg" />
        Your browser does not support the audio element.
      </audio>
    </div>

    <div>
      <%= simple_form_for @setting, url: '', as: 'setting',
        wrapper: :inline_form,
        html: { class: 'form-inline' } do |f| %>
        <%#= f.error_notification %>
        <% html_attrs = {style: "width: 50px;", maxlength: 2} %>
        Play for
        <%= f.input :play_time, input_html: html_attrs %> seconds,
        pause for
        <%= f.input :pause_time, input_html: html_attrs %> seconds,
        rewind for
        <%= f.input :rewind_time, input_html: html_attrs %> seconds.

        <%#= f.button :submit %>
      <% end %>
    </div>

    <div>
      <button type="button" class="btn btn-default" id="playPauseButton">
        <span class="glyphicon glyphicon-play" aria-hidden="true"></span>
      </button>
    </div>
  </div>
</div>


<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @episode.name %>
</p>

<p>
  <strong>Podcast:</strong>
  <%= link_to @episode.podcast.name, @episode.podcast %>
</p>

<%= link_to 'Edit', edit_podcast_episode_path(@podcast, @episode) %> |
<%= link_to 'Back', podcast_episodes_path(@podcast) %>


<script>
  $(document).on("page:change", function() {
    var audio = $('#audioPlayer');
    audio.bind('load', function() {
      // alert("loaded");
      // audio.play;

    }).bind('durationchange', function() {
      // alert("Duration: " + audio.prop('duration'));
    }).bind('playing', function() {
      // audio has started playing. Either for the first time, or after being paused.
      switchPlayPauseIcon('pause');
    }).bind('pause', function() {
      // audio has been paused
      switchPlayPauseIcon('play');
    }).bind('play', function() {
      // playing starts after being paused
    }).bind('ended', function() {
      // playback has completed
    }).bind('error', function(e) {
      // console.log(e);
    });

    audio.trigger('load');

    $('#playPauseButton').on('click', function() {
      playPause(audio);
    });

    function switchPlayPauseIcon(new_status) {
      old_status = (new_status == 'play' ? 'pause' : 'play');
      // $('#playPauseButton span').switchClass("glyphicon-"+old_status, "glyphicon-"+new_status);
      $('#playPauseButton span').removeClass("glyphicon-"+old_status).addClass("glyphicon-"+new_status);
    }

    // Toggles between playing and paused
    function playPause(player) {
      playerDom = player[0]
      action = (playerDom.paused ? 'play' : 'pause');
      player.trigger(action);
    }

    $(document).on("keypress", function(e) {
      // console.log(e.keyCode);
      if (e.keyCode == 112) {
        // console.log("p pressed");
        // console.log('p'.charCodeAt(0));
      }
      if (e.metaKey) {
        // console.log("meta");
      }
      if(e.metaKey && e.keyCode == 'p'.charCodeAt(0)){
        e.preventDefault();
        playPause(audio);
      }
    });
  });
</script>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Podscribe', root_path, class: 'navbar-brand' %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav navbar-right">
        <%= render 'layouts/navigation_links' %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<li><%= link_to 'Search', search_podcasts_path %></li>
<li><%= link_to 'Podcasts', podcasts_path %></li>
<li><%= link_to 'About', page_path('about') %></li>
<li><%= link_to 'Feedback', 'http://tenderapp.com' %></li>

<% if user_signed_in? %>
  <li class="dropdown">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><%= current_user.name %> <span class="caret"></span></a>
    <ul class="dropdown-menu" role="menu">
      <li><%= link_to "My Account", edit_user_path(current_user) %></li>
      
      <% if current_user.admin? %>
        <li class="divider"></li>
        <li>Admin</li>
        <li><%= link_to 'Users', users_path %></li>
        <li><%= link_to 'Sidekiq', sidekiq_web_path %></li>
      <% end %>
      
      <li class="divider"></li>
      <li><%= link_to 'Sign Out', signout_path %></li>
    </ul>
  </li>
<% else %>
  <li><%= link_to 'Sign in', signin_path %></li>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Podscribe" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Podscribe" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body id="page-top" class="c-<%= controller_name %> a-<%= action_name %>">
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
      <div class="container">
       <%= render 'layouts/messages' %>
       <%= yield %>
      </div>
    </main>
    <footer>
      <%= render 'shared/footer' %>
    </footer>
  </body>
</html>

app/views/pages/about.html.erb
<% content_for :title do %>About<% end %>
<h3>About the Website</h3>
<p>
This web application was created with
<%= link_to('Rails Composer', 'http://railsapps.github.io/rails-composer/') %>
from the <%= link_to('RailsApps project', 'http://railsapps.github.io/') %>.
</p>

app/views/pages/episode.html.erb
<% content_for :title do %>Episode<% end %>

<div class="row">
  <div class="text-center">
    <h3>Podcast Episode - Test UI</h3>
    <div>
      <audio class="" id="audioPlayer" controls preload="none">
        <!-- <source src="track.ogg" type="audio/ogg" /> -->
        <source src="http://traffic.libsyn.com/atpfm/atp131.mp3" type="audio/mpeg" />
        Your browser does not support the audio element.
      </audio>
    </div>

    <div>
    <% @setting = AudioSetting.new(3, 5, 4) %>
      <%= simple_form_for @setting, url: '', as: 'setting',
        wrapper: :inline_form,
        html: { class: 'form-inline' } do |f| %>
        <%#= f.error_notification %>
        Play for
        <%= f.input :play_time %> seconds,
        pause for
        <%= f.input :pause_time %> seconds,
        rewind for
        <%= f.input :rewind_time %> seconds.

        <%= f.button :submit %>
      <% end %>
    </div>

    <div>
      <button type="button" class="btn btn-default" id="playButton">
        <span class="glyphicon glyphicon-play" aria-hidden="true"></span>
      </button>

      <button type="button" class="btn btn-default" id="pauseButton">
        <span class="glyphicon glyphicon-pause" aria-hidden="true"></span>
      </button>
    </div>
  </div>
</div>

app/views/pages/home.html.erb
<div class="row">
  <div class="text-center">
    <h1>Podcast + Transcribe = Podscribe</h1>
    <h3>Where Crowdsourcing meets Podcast Transcription</h3>
    <hr>
    <h3>Help Transcribe your favorite Podcasts now!</h3>
    
  </div>
</div>

<%= render 'podcasts/search' %>
<%# Ideas for launch page: http://www.smashingmagazine.com/2011/09/elements-of-a-viral-launch-page/ %>

app/views/podcasts/_form.html.erb
<%= simple_form_for(@podcast) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :rss_feed %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/podcasts/_search.html.erb
<div class="row">
  <div class="text-center">
    <div class="jumbotron green-bg">
      <form id="search_itunes" class="form-inline">
        <div class="form-group">
          <input type="text" class="form-control" id="search_term" placeholder="Enter a podcast Name" size="70">
        </div>
        <div class="form-group">
          <select class="form-control" id="search_country">
            <option value="US">United States</option>
            <option value="CA">Canadia</option>
          </select>
        </div>
        <br /><br />
        <button type="submit" class="btn btn-warning btn-lg">Search iTunes!</button>
        <div id="search_error"></div>
      </form>
    </div>
  </div>
</div>


<div id="search_results" class="row hide">
  <div class="col-md-12">
    <h4>Found <span id="result_count"></span> podcasts</h4>
  </div>
  <div id="search_results_row" class="col-lg-12">
    <div class="item-episode hide">
      <img src="" />
      <div class="info">
        <a class="btn btn-block" href="">Set This Feed</a>
      </div>
      <div class="title">
        <h4><a href="">Accidental Tech Podcast</a></h4>
      </div>
    </div>
  </div>
</div>


<script>
  $(function() {
    $('#search_itunes').on('submit', function(e) {
      e.preventDefault();
      var search_term = $('#search_term').val();
      var country     = $('#search_country').val();
      var media       = 'podcast';
      if (search_term != '') {
        $('#search_error').html('');
        $.ajax({
          url: "https://itunes.apple.com/search",
          data: { term: search_term, country: country, media: media },
          dataType: 'JSONP'
          })
          .done(function(data) {
            $('#search_results').removeClass('hide');
            $('#result_count').html(data.resultCount);
            $.each(data.results, function(index, item) {
              $div = $('.item-episode.hide').clone().removeClass('hide');
              $div.children('img').attr('src', item.artworkUrl60);
              $div.appendTo('#search_results_row');
              // console.log('collectionId: ' + item.collectionId);
              // console.log('artistName: ' + item.artistName);
              // console.log('collectionCensoredName: ' + item.collectionCensoredName);
              // console.log('feedUrl: ' + item.feedUrl);
              // console.log('artworkUrl30: ' + item.artworkUrl30);
              // console.log('primaryGenreName: ' + item.primaryGenreName);
            });
          })
          .fail(function(data) {
            console.log(data);
          })
      } else {
        $('#search_results').addClass('hide');
        $('#search_error').html("Please enter something to search for");
      }
    });
  });
</script>

app/views/podcasts/edit.html.erb
<h1>Editing Podcast</h1>

<%= render 'form' %>

<%= link_to 'Show', @podcast %> |
<%= link_to 'Back', podcasts_path %>

app/views/podcasts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Podcasts</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Episodes</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @podcasts.each do |podcast| %>
      <tr>
        <td><%= podcast.name %></td>
        <td><%= link_to 'Episodes', podcast_episodes_path(podcast) %></td>
        <td><%= link_to 'Show', podcast %></td>
        <td><%= link_to 'Edit', edit_podcast_path(podcast) %></td>
        <td><%= link_to 'Destroy', podcast, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Podcast', new_podcast_path %>

app/views/podcasts/new.html.erb
<h1>New Podcast</h1>

<%= render 'form' %>

<%= link_to 'Back', podcasts_path %>

app/views/podcasts/search.html.erb
<div class="row">
  <div class="text-center">
    <h2>Find any Podcast in iTunes</h2>
  </div>
</div>

<%= render 'search' %>

app/views/podcasts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @podcast.name %>
</p>

<p>
  <strong>Rss feed:</strong>
  <%= @podcast.rss_feed %>
</p>

<%= link_to 'Edit', edit_podcast_path(@podcast) %> |
<%= link_to 'Back', podcasts_path %>

app/views/shared/_footer.html.erb
<div class="container">
  <div class="text-center">
    <div>
      <a href="https://twitter.com/podscribe" class="twitter-follow-button" data-show-count="false" data-size="large">Follow @podscribe</a> <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+'://platform.twitter.com/widgets.js';fjs.parentNode.insertBefore(js,fjs);}}(document, 'script', 'twitter-wjs');</script>
    </div>
  </div>
</div>
<!-- <div class="row">
  
</div> -->

app/views/shared/_mailchimp_teaser.html.erb
<div class="col-md-6 col-md-offset-3">
  <!-- Begin MailChimp Signup Form -->
  <link href="//cdn-images.mailchimp.com/embedcode/classic-081711.css" rel="stylesheet" type="text/css">
  <style type="text/css">
    #mc_embed_signup{background:#fff; font:14px Helvetica,Arial,sans-serif;}
    /* Add your own MailChimp form style overrides in your site stylesheet or in this style block.
       We recommend moving this block and the preceding CSS link to the HEAD of your HTML file. */
  </style>
  <div id="mc_embed_signup">
  <form action="//podscribe.us11.list-manage.com/subscribe/post?u=64fb467e05dfca5d9c027a1a6&amp;id=0c2c6b84c7" method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form" class="validate" target="_blank" novalidate>
      <div id="mc_embed_signup_scroll">
        <h2>Send me email updates about Podscribe</h2>
  <div class="mc-field-group">
    <label for="mce-EMAIL">Email Address </label>
    <input type="email" value="" name="EMAIL" class="required email" id="mce-EMAIL">
  </div>
    <div id="mce-responses" class="clear">
      <div class="response" id="mce-error-response" style="display:none"></div>
      <div class="response" id="mce-success-response" style="display:none"></div>
    </div>    <!-- real people should not fill this in and expect good things - do not remove this or risk form bot signups-->
      <div style="position: absolute; left: -5000px;"><input type="text" name="b_64fb467e05dfca5d9c027a1a6_0c2c6b84c7" tabindex="-1" value=""></div>
      <div class="clear"><input type="submit" value="Subscribe" name="subscribe" id="mc-embedded-subscribe" class="button"></div>
      </div>
  </form>
  </div>
  <script type='text/javascript' src='//s3.amazonaws.com/downloads.mailchimp.com/js/mc-validate.js'></script><script type='text/javascript'>(function($) {window.fnames = new Array(); window.ftypes = new Array();fnames[0]='EMAIL';ftypes[0]='email';fnames[1]='FNAME';ftypes[1]='text';fnames[2]='LNAME';ftypes[2]='text';}(jQuery));var $mcj = jQuery.noConflict(true);</script>
  <!--End mc_embed_signup-->
</div>

app/views/users/_user.html.erb
<td>
  <%= link_to user.email, user %>
</td>
<td>
  <%= form_for(user) do |f| %>
    <%= f.select(:role, User.roles.keys.map {|role| [role.titleize,role]}) %>
    <%= f.submit 'Change Role', :class => 'button-xs' %>
  <% end %>
</td>
<td>
  <%= link_to("Delete user", user_path(user), :data => { :confirm => "Are you sure?" }, :method => :delete, :class => 'button-xs') unless user == current_user %>
</td>

app/views/users/index.html.erb
<div class="container">
  <div class="row">
    <h3>Users</h3>
    <div class="column">
      <table class="table">
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <%= render user %>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<h3>User</h3>
<p>Name: <%= @user.name if @user.name %></p>

app/views/visitors/index.html.erb
<h3>Welcome</h3>
<p><%= link_to 'Users:', users_path %> <%= User.count %> registered</p>